name = "file-share"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2023-10-02"
assets = { directory = "./public" }

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "fileShare"
id = "b9e8166f965944fbb508abbf4beaf8c2"
