name = "file-share"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2023-10-02"
assets = { directory = "./public" }

[placement]
mode = "smart"

[[kv_namespaces]]
binding = "file_share_data"
id = "8191219ff37748b8b45b57c07296adca"
